#include "nsISupports.idl"

[scriptable, uuid(cacd1518-d892-4c8c-9e95-f37519be51b1)]
interface IInputMethod : nsISupports
{
  readonly attribute AString readableString;

  void useCurrent();
  void setAsCurrent();

  attribute boolean enabled;
  attribute AString keyboardLayout;

  attribute boolean openStatus;

  const long CMODE_ALPHANUMERIC = 0x0000;
  const long CMODE_NATIVE = 0x0001;
  const long CMODE_CHINESE = CMODE_NATIVE;
  const long CMODE_HANGEUL = CMODE_NATIVE;
  const long CMODE_HANGUL = CMODE_NATIVE;
  const long CMODE_JAPANESE = CMODE_NATIVE;
  const long CMODE_KATAKANA = 0x0002;  // only effect under CMODE_NATIVE
  const long CMODE_LANGUAGE = 0x0003;
  const long CMODE_FULLSHAPE = 0x0008;
  const long CMODE_ROMAN = 0x0010;
  const long CMODE_CHARCODE = 0x0020;
  const long CMODE_HANJACONVERT = 0x0040;
  const long CMODE_SOFTKBD = 0x0080;
  const long CMODE_NOCONVERSION = 0x0100;
  const long CMODE_EUDC = 0x0200;
  const long CMODE_SYMBOL = 0x0400;
  const long CMODE_FIXED = 0x0800;
  
  attribute long convMode;
  
  const long SMODE_NONE = 0x0000;
  const long SMODE_PLAURALCLAUSE = 0x0001;
  const long SMODE_SINGLECONVERT = 0x0002;
  const long SMODE_AUTOMATIC = 0x0004;
  const long SMODE_PHRASEPREDICT = 0x0008;
  const long SMODE_CONVERSATION = 0x0010;

  attribute long sentMode;
};

//
// This interfaces is implemented in JavaScript
//
[scriptable, uuid(f26f72b6-2ba2-4ccc-ba38-a8940e286fc4)]
interface ITabInputMethodManager : nsISupports
{
  void setTabInputMethod(in string tabKey, in IInputMethod inputMethod);
  IInputMethod getTabInputMethod(in string tabKey);

  attribute IInputMethod defaultInputMethod;
};

[scriptable, uuid(081f8e2a-8c1a-4149-9de7-6d75f716825e)]
interface ITabImSwitchApp : nsISupports
{
  const long USE_AUTODETECT = 0;
  const long USE_DEFAULT = 1;
  const long USE_MULTILINGUAL = 2;

  attribute long multilingualPolicy;
  readonly attribute boolean multilingual;

  void init();

  //
  // To solve the problem of MSPY2003 with XP En.
  //
  boolean hasMSPY();

  readonly attribute AString inputMethodList;
  readonly attribute wchar listSeparator;
};

[scriptable, uuid(cb6c1b65-e377-42f6-8f9d-6b5ce67350ff)]
interface IDebugLogger : nsISupports
{
  void init(in string logFile);
  attribute long logLevel;
  void writeLog(in long level, in string message);
};

