#include "nsISupports.idl"

//
// These interfaces will be implemented in C++.
//
[scriptable, uuid(081f8e2a-8c1a-4149-9de7-6d75f716825e)]
interface ITabImSwitchApp : nsISupports
{
  attribute AString currentKeyboardLayoutName;
};

//
// These interfaces will be implemented in JavaScript
//
[scriptable, uuid(f26f72b6-2ba2-4ccc-ba38-a8940e286fc4)]
interface ITabInputMethodManager : nsISupports
{
  void setTabInputMethod(in string tabKey, in string inputMethod);
  string getTabInputMethod(in string tabKey);

  attribute string defaultInputMethod;
};
